hobbies = [
    "Reading", "Traveling", "Painting", "Gardening", "Cooking", "Running", "Swimming", "Cycling",
    "Hiking", "Photography", "Dancing", "Writing", "Fishing", "Camping", "Yoga",
    "Skiing", "Surfing", "Rock Climbing", "Bird Watching", "Star Gazing", "Pottery", "Knitting",
    "Sculpture", "Archery", "Basketball", "Baseball", "Soccer", "Football", "Rugby", "Sailing",
    "Baking", "Piano", "Guitar", "Violin", "Drums", "Harmonica", "Saxophone", "Beatboxing",
    "Singing", "Storytelling", "Magic Tricks", "Origami", "Chess", "Puzzles", "Board Games",
    "Video Games", "Movies", "Music", "Podcasts", "Volunteering", "Blogging", "Vlogging",
    "Coding", "Meditation", "Weightlifting", "Boxing", "Martial Arts", "Ballet", "Theater",
    "Drama", "Drawing", "Graphic Design", "Interior Design", "Fashion", "Makeup", "Tattoos",
    "Piercing", "Wine Tasting", "Beer Brewing", "Coffee Roasting", "Collecting", "Shopping",
    "Thrifting", "Restoration", "DIY", "Home Improvement", "Jewelry Making", "Tattooing",
    "Card Games", "Stand-Up Comedy", "Impersonations", "Public Speaking", "Creative Writing",
    "Radio Broadcasting", "Podcast Hosting", "Social Media", "Networking", "Investing",
    "Entrepreneurship", "Mentoring", "Modeling", "Youtubing", "Streaming", "Astrology",
    "Tarot Reading", "Mysticism", "Religion", "Spirituality", "Philosophy", "Political Debates",
    "Languages", "Culture Studies", "History", "Anthropology", "Archaeology", "Paleontology",
    "Geology", "Meteorology", "Astronomy", "Biology", "Chemistry", "Physics", "Mathematics",
    "Cooking", "Nutrition", "Dieting", "Veterinary", "Botany", "Environmentalism", "Recycling",
    "Composting", "Zero Waste", "Minimalism", "Organizing", "Productivity", "Life Hacks",
    "Life Coaching", "Fitness", "Health", "Beauty", "Hygiene", "Aromatherapy", "Holistic Health",
    "Natural Remedies", "Medical Research", "Forensics", "Criminology", "Psychology",
    "Sociology", "Human Rights", "Social Justice", "Activism", "Charity", "Humanitarianism"
]

comments = [
    "Cheerful and joyous message.",
    "Message in a funny style.",
    "Emphasize strong friendship.",
    "Focus on bright future.",
    "Professional style message.",
    "Include wisdom quote.",
    "Fun and excitement for a child.",
    "Appreciate their qualities.",
    "For a travel enthusiast.",
    "For a sports lover.",
    "Mention their pet.",
    "Poetic style message.",
    "Acknowledge their impact in your life.",
    "For a fantasy book lover.",
    "For a nature lover.",
    "Highlight their courage.",
    "Artistic style message.",
    "For a foodie.",
    "Mention their passion for music.",
    "For a movie enthusiast.",
    "Message with a tone of adventure.",
    "Acknowledge their kindness.",
    "Elegant style message.",
    "For a bookworm.",
    "For a pet lover.",
    "Highlight their humor.",
    "Romantic style message.",
    "For a photography enthusiast.",
    "Mention their love for dance.",
    "For a coffee lover.",
    "Message with a tone of mystery.",
    "Acknowledge their intelligence.",
    "Rustic style message.",
    "For a history buff.",
    "For a gamer.",
    "Highlight their generosity.",
    "Modern style message.",
    "For a fashion enthusiast.",
    "Mention their love for gardening.",
    "For a tea lover.",
    "Message with a tone of nostalgia.",
    "Acknowledge their creativity.",
    "Vintage style message.",
    "For a science enthusiast.",
    "For a tech lover.",
    "Highlight their leadership.",
    "Sophisticated style message.",
    "For a fitness enthusiast.",
    "Mention their love for the outdoors.",
    "For a wine enthusiast."
]
