# fly.toml app configuration file generated for birthday-greetings-ai on 2023-07-29T23:46:00+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "birthday-greetings-ai"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
